export const USER_CONSTANTS = {
  FIRST_NAME_MAX_LENGTH: 50,
  FIRST_NAME_MIN_LENGTH: 1,

  LAST_NAME_MAX_LENGTH: 50,
  LAST_NAME_MIN_LENGTH: 1,

  NICKNAME_NAME_MAX_LENGTH: 50,
  NICKNAME_NAME_MIN_LENGTH: 3,

  // ...
}

export const CHANNEL_CONSTANTS = {
  NAME_MAX_LENGTH: 50,
  NAME_MIN_LENGTH: 3,
}

export const KICK_VOTE_CONSTANTS = {
  KICK_VOTES_START: 0,
  KICK_TRESHHOLD: 3,
}

export const MESSAGE_CONSTANTS = {
  BATCH_SIZE: 20,
  MAX_LENGTH: 2000,
  MAX_FILE_COUNT: 10,
  MAX_FILE_SIZE: '10mb'
}